#!/usr/bin/env node
/**
 * Setup helper for GeoGrandmasters Agent
 * Guides through initial configuration
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { createInterface } from 'readline';

const rl = createInterface({
  input: process.stdin,
  output: process.stdout
});

const question = (prompt) => new Promise(resolve => rl.question(prompt, resolve));

console.log(`
╔════════════════════════════════════════════════════════╗
║   GeoGrandmasters Agent Setup                          ║
║   SuperColony Verified Intelligence Relay                 ║
╚════════════════════════════════════════════════════════╝
`);

async function setup() {
  // Check if .env exists
  if (existsSync('.env')) {
    const overwrite = await question('⚠️  .env already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Setup cancelled.');
      rl.close();
      return;
    }
  }

  console.log('\n📋 Step 1: Demos Wallet');
  console.log('You need a 12-word mnemonic for your agent\'s identity.');
  console.log('Generating one for you...\n');

  // Generate wallet
  const { Demos } = await import('@kynesyslabs/demosdk/websdk');
  const demos = new Demos();
  const mnemonic = demos.newMnemonic(128);
  const tempWallet = demos.newWalletFromMnemonic(mnemonic);
  const address = tempWallet.address;

  console.log(`✓ Generated wallet`);
  console.log(`  Address: ${address}`);
  console.log(`  Mnemonic: ${mnemonic}`);
  console.log(`\n⚠️  SAVE THIS MNEMONIC SECURELY!`);
  console.log(`   It cannot be recovered if lost.\n`);

  console.log('📋 Step 2: Fund Your Wallet');
  console.log(`Visit: https://faucet.demos.sh/`);
  console.log(`Enter address: ${address}`);
  console.log(`Or run: curl -X POST https://faucetbackend.demos.sh/api/request \\\n  -H "Content-Type: application/json" \\\n  -d '{"address": "${address}"}'\n`);

  const funded = await question('Have you funded the wallet? (y/N): ');
  if (funded.toLowerCase() !== 'y') {
    console.log('\n⚠️  Please fund the wallet before running the agent.');
    console.log('You can continue setup and fund later.\n');
  }

  console.log('\n📋 Step 3: Telegram Bot');
  console.log('1. Message @BotFather on Telegram');
  console.log('2. Run /newbot and follow instructions');
  console.log('3. Copy the bot token\n');

  const botToken = await question('Enter your Telegram bot token: ');

  if (!botToken || botToken.length < 30) {
    console.log('\n⚠️  That doesn\'t look like a valid bot token.');
    console.log('You can edit .env later to add the correct token.\n');
  }

  console.log('\n📋 Step 4: Channel Configuration');
  const channel = await question('Channel to monitor (no default — enter username without @): ');
  const channelName = channel.trim() ? `@${channel.trim().replace(/^@/, '')}` : '';

  console.log(`\n✓ Configuration complete!`);
  console.log(`  Channel: ${channelName}`);

  // Create .env
  const envContent = `# Generated by setup script on ${new Date().toISOString()}
# Your agent's Demos wallet mnemonic (12 words) - KEEP SECRET!
DEMOS_MNEMONIC=${mnemonic}

# Demos node RPC endpoint
DEMOS_RPC_URL=https://demosnode.discus.sh/

# SuperColony/SuperColony API URL
COLONY_URL=https://www.supercolony.ai

# Telegram Bot Token (get from @BotFather)
TELEGRAM_BOT_TOKEN=${botToken || 'your_token_here'}

# Telegram channel to monitor
TELEGRAM_CHANNEL=${channelName}

# How often to check for new messages (milliseconds)
CHECK_INTERVAL_MS=60000
`;

  writeFileSync('.env', envContent);
  console.log('\n✓ Created .env file');

  console.log(`
╔════════════════════════════════════════════════════════╗
║   Setup Complete!                                      ║
╚════════════════════════════════════════════════════════╝

Next steps:
1. Add your bot as admin to ${channelName}
2. Run: npm start

Your agent will:
• Monitor ${channelName} for new posts
• Attest any URLs with DAHR proof
• Publish to SuperColony with verification

Agent Profile:
  Name: geo-grandmasters-relay
  Address: ${address}
  Network: Demos Testnet

Dashboard: https://www.supercolony.ai
Explorer: https://scan.demos.network/address/${address}
`);

  rl.close();
}

setup().catch(err => {
  console.error('Setup error:', err);
  rl.close();
  process.exit(1);
});
